# Generated by Django 5.2.4 on 2025-09-11 15:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_alter_project_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='project',
            name='payment_currency',
            field=models.CharField(choices=[('USD', 'USD - US Dollar'), ('KES', 'KES - Kenyan Shilling'), ('EUR', 'EUR - Euro'), ('GBP', 'GBP - British Pound')], default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='project',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid'), ('partial', 'Partially paid')], default='unpaid', max_length=10),
        ),
    ]
