# Generated by Django 5.2.4 on 2025-09-15 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_project_payment_amount_project_payment_currency_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
